# Generated by Django 5.1.3 on 2024-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.JSONField(null=True),
        ),
    ]
